# Postgresql

In [44]:
from pathlib import Path
import json
import pandas as pd

# Afficher toutes les colonnes (sans limite)
pd.set_option("display.max_columns", None)

## Récupérer données normalisées

In [45]:
def recuperer_recent(chemin_dossier)  -> list :
    '''
    Récupérer le chemin du document json le plus récent.
    Entrée : chemin du dossier visé
    Sortie : chemin du fichier horodaté le plus récent
    '''
    fichiers = []
    if chemin_dossier.exists():
        fichiers_ft = sorted(chemin_dossier.glob("*.json"))
        if fichiers_ft:
            fichiers.append(str(fichiers_ft[-1]))  # le plus récent  
    return fichiers[0]
#====================================================================================s
def charger_offres(chemin_fichier):
    '''
    Charger les offres du chemin du fichier json renseigné en paramètre
    '''
    try:
        with open(chemin_fichier, "r", encoding="utf-8") as f:
            offres = json.load(f)
        print(f"  {chemin_fichier} → {len(offres)} offres")
        return offres
    except Exception as e:
        print(f"  Erreur chargement {chemin_fichier} : {e}")

In [46]:
# ── Étape 1 : Récupération du nom du fichier le plus récent ──────────────────────────────
chemin_fichier_normalise = recuperer_recent(Path("../data/processed/normalise"))

# ── Étape 2 : Récupération des offres dans Python (liste de dictionnaires) ──────────────
# Offres normalisées
offres_normalisees =  charger_offres(chemin_fichier_normalise)

  ../data/processed/normalise/offres_20260408_224410.json → 120 offres

## Création dataframes Pandas

In [47]:
def rechercher_duplicates(df):
    # Check number of rows before removing duplicates
    print(f"Number of rows : {len(df)}\n")

    # # Compute the number of duplicated rows
    # print(f"Number of duplicated rows : {df.duplicated().sum()}\n")

# =====================================================================================

def get_missing_data(data):       
    # Counting the percentage of NaN for each column
    missing_data = data.isnull().sum().sort_values(ascending=False)/len(data)*100 #NaN percentage for each column

    # missing_data
    missing_data = missing_data[missing_data > 0]

    #Missing data column names
    missing_cols = missing_data.index.values.tolist()

    #Show missing data in percent
    if len(missing_data)>0:
        print("missing data (isnull) detected are as follows:")
        display(missing_data)
    else:
        display("no missing data detected\n")

# =====================================================================================

def explore(df):
    #Numerical Features
    numerical_features = df.select_dtypes(include = 'number').columns.values.tolist()
    
    print(f"Shape is : {df.shape}\n")

    display(df.sample(5))

    display(df.info())
    print("\n")
    
    if numerical_features:
        print("Description is : \n")
        display(df.describe())
    else : 
        print("No numerical features to describe.\n")

    get_missing_data(df)

In [48]:
df = pd.DataFrame(offres_normalisees)
df.head(3)

,id,source,url,titre,entreprise,description,competences,localisation_ville,localisation_dept,latitude,longitude,type_contrat,teletravail,salaire_min,salaire_max,salaire_devise,experience_min,secteur,sous_secteur,rome_code,nb_employes,missions,avantages,qualification,date_publication,date_extraction
0,ft_206PTWH,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,EPSYL,"A compétences égales, le poste est ouvert à to...",[],Lyon 01,69001,45.769506,4.830081,CDI,NaN,38000.0,45000.0,EUR,3.0,Conseil en systèmes et logiciels informatiques,,M1811,50 à 99 salariés,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564752
1,ft_1235851,francetravail,https://candidat.francetravail.fr/offres/reche...,Responsable merger and acquisition,NaN,<p>Safran est un groupe international de haute...,[],Montereau-Sur-Le-Jard,77950,48.597229,2.686574,CDI,NaN,NaN,NaN,EUR,NaN,,,M1219,None,[],[],,2026-04-08,2026-04-08T22:44:10.564770
2,ft_1230254,francetravail,https://candidat.francetravail.fr/offres/reche...,Développeur / Développeuse IA,NaN,\n Rejoignez Atos et sa practice Ra...,[],Bezons,95870,48.927790,2.216126,CDI,NaN,NaN,NaN,EUR,5.0,,,M1889,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564777

In [49]:
# Colonnes qui contiennent des listes
list_cols = ["competences","missions","avantages"]
list_cols

['competences', 'missions', 'avantages']

In [77]:
df.head(56)

,id,source,url,titre,entreprise,description,competences,localisation_ville,localisation_dept,latitude,longitude,type_contrat,teletravail,salaire_min,salaire_max,salaire_devise,experience_min,secteur,sous_secteur,rome_code,nb_employes,missions,avantages,qualification,date_publication,date_extraction
0,ft_206PTWH,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,EPSYL,"A compétences égales, le poste est ouvert à to...",[],Lyon 01,69001,45.769506,4.830081,CDI,NaN,38000.0,45000.0,EUR,3.0,Conseil en systèmes et logiciels informatiques,,M1811,50 à 99 salariés,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564752
1,ft_1235851,francetravail,https://candidat.francetravail.fr/offres/reche...,Responsable merger and acquisition,NaN,<p>Safran est un groupe international de haute...,[],Montereau-Sur-Le-Jard,77950,48.597229,2.686574,CDI,NaN,NaN,NaN,EUR,NaN,,,M1219,None,[],[],,2026-04-08,2026-04-08T22:44:10.564770
2,ft_1230254,francetravail,https://candidat.francetravail.fr/offres/reche...,Développeur / Développeuse IA,NaN,\n Rejoignez Atos et sa practice Ra...,[],Bezons,95870,48.927790,2.216126,CDI,NaN,NaN,NaN,EUR,5.0,,,M1889,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564777
3,ft_1230212,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,NaN,\n Description de l'entrepriseSopra...,[],Nantes,44000,47.206511,-1.588370,CDD,NaN,NaN,NaN,EUR,0.0,,,M1811,None,[],[],Technicien,2026-04-08,2026-04-08T22:44:10.564782
4,ft_1230138,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,NaN,\n Description de l'entrepriseSopra...,[],Nantes,44000,47.206511,-1.588370,CDD,NaN,NaN,NaN,EUR,0.0,,,M1811,None,[],[],Technicien,2026-04-08,2026-04-08T22:44:10.564787
5,ft_1230109,francetravail,https://candidat.francetravail.fr/offres/reche...,Big data engineer,NaN,\n Ce que vous allez faire si vous...,[],Caen,14000,49.193554,-0.390440,CDI,NaN,NaN,NaN,EUR,2.0,,,M1811,None,[],[],Technicien,2026-04-08,2026-04-08T22:44:10.564791
6,ft_1229702,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,NaN,\n Description de l'entrepriseDescr...,[],Nantes,44000,47.206511,-1.588370,CDI,NaN,NaN,NaN,EUR,0.0,,,M1811,None,[],[],Technicien,2026-04-08,2026-04-08T22:44:10.564795
7,ft_1229568,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,NaN,\n Vos missions à nos côtés :• Co...,[],Bezons,95870,48.927790,2.216126,CDI,NaN,NaN,NaN,EUR,5.0,,,M1811,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564799
8,ft_1228694,francetravail,https://candidat.francetravail.fr/offres/reche...,Architecte de données informatiques,JEMS,RESPONSABILITÉS : \n\nNous recherchons un(e) ...,[],Levallois-Perret,92300,48.892818,2.287751,CDI,NaN,45000.0,55000.0,EUR,NaN,,,M1811,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564804
9,ft_1228307,francetravail,https://candidat.francetravail.fr/offres/reche...,Ingénieur / Ingénieure travaux,REEL IT,RESPONSABILITÉS : \n\nContexte\nDans le cadre ...,[],Aix-En-Provence,13080,43.503601,5.385526,CDI,NaN,38000.0,45000.0,EUR,NaN,,,F1137,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564808
10,ft_1228236,francetravail,https://candidat.francetravail.fr/offres/reche...,Ingénieur / Ingénieure travaux,REEL IT,RESPONSABILITÉS : \n\nContexte\nDans le cadre ...,[],Nice,06000,43.677218,7.205156,CDI,NaN,38000.0,45000.0,EUR,NaN,,,F1137,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564812
11,ft_1228231,francetravail,https://candidat.francetravail.fr/offres/reche...,Ingénieur / Ingénieure travaux,REEL IT,RESPONSABILITÉS : \n\nContexte\nDans le cadre ...,[],Toulouse,31000,43.597868,1.430199,CDI,NaN,38000.0,45000.0,EUR,NaN,,,F1137,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564817
12,ft_1228138,francetravail,https://candidat.francetravail.fr/offres/reche...,Ingénieur / Ingénieure travaux,REEL IT,RESPONSABILITÉS : \n\nContexte\nDans le cadre ...,[],Montpellier,34000,43.615688,3.930282,CDI,NaN,38000.0,45000.0,EUR,NaN,,,F1137,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564821
13,ft_1228121,francetravail,https://candidat.francetravail.fr/offres/reche...,Ingénieur / Ingénieure travaux,REEL IT,RESPONSABILITÉS : \n\nContexte\nDans le cadre ...,[],Paris,NaN,NaN,NaN,CDI,NaN,38000.0,45000.0,EUR,NaN,,,F1137,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564825
14,ft_1227923,francetravail,https://candidat.francetravail.fr/offres/reche...,Ingénieur / Ingénieure travaux,REEL IT,RESPONSABILITÉS : \n\nContexte\nDans le cadre ...,[],Lille,59000,50.619413,3.031632,CDI,NaN,38000.0,45000.0,EUR,NaN,,,F1137,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564829
15,ft_1227904,francetravail,https://candidat.francetravail.fr/offres/reche...,Ingénieur / Ingénieure travaux,REEL IT,RESPONSABILITÉS : \n\nContexte\nDans le cadre ...,[],Lyon 9E Arrondissement,69009,45.786154,4.796312,CDI,NaN,38000.0,45000.0,EUR,NaN,,,F1137,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564833
16,ft_1227856,francetravail,https://candidat.francetravail.fr/offres/reche...,Architecte de données informatiques,ALTECA,RESPONSABILITÉS : \n\nDans le cadre d'une miss...,[],Strasbourg,67000,48.594935,7.718742,CDI,NaN,NaN,NaN,EUR,3.0,,,M1811,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564837
17,ft_1227207,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,Hays France,Responsabilités principales : Modélisation de ...,[],Marseille 1Er Arrondissement,13001,43.298344,5.383221,CDI,NaN,45000.0,60000.0,EUR,8.0,Autres activités informatiques,,M1811,None,[],[],,2026-04-08,2026-04-08T22:44:10.564842
18,ft_1226357,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,NaN,Le métier de Platform Data Engineer est fait p...,[],Paris,NaN,NaN,NaN,CDI,NaN,NaN,NaN,EUR,NaN,,,M1811,None,[],[],,2026-04-08,2026-04-08T22:44:10.564846
19,ft_1226328,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,NaN,Votre profil :Issu(e) d'une formation Bac&amp;...,[],Clermont-Ferrand,63000,45.791423,3.113126,CDI,NaN,NaN,NaN,EUR,NaN,,,M1811,None,[],[],,2026-04-08,2026-04-08T22:44:10.564850
20,ft_1230264,francetravail,https://candidat.francetravail.fr/offres/reche...,Développeur / Développeuse data,NaN,\n Rejoignez la communauté Data d’A...,[],Bordeaux,33000,44.832810,-0.611465,CDI,NaN,NaN,NaN,EUR,2.0,,,M1811,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564854
21,ft_1226289,francetravail,https://candidat.francetravail.fr/offres/reche...,Big data engineer,NaN,Consultant(e) Cloud Data &amp; Modernisation A...,[],Montpellier,34000,43.615688,3.930282,CDI,NaN,NaN,NaN,EUR,NaN,,,M1811,None,[],[],,2026-04-08,2026-04-08T22:44:10.564858
22,ft_1226288,francetravail,https://candidat.francetravail.fr/offres/reche...,Big data engineer,NaN,Consultant(e) Cloud Data &amp; Modernisation A...,[],Tours,37000,47.404397,0.710983,CDI,NaN,NaN,NaN,EUR,NaN,,,M1811,None,[],[],,2026-04-08,2026-04-08T22:44:10.564862
23,ft_206QNMQ,francetravail,https://candidat.francetravail.fr/offres/reche...,Analyste qualité des données,WINSIDE TECHNOLOGY AURA,Contexte de la mission: \n\nDans le cadre de l...,"[Analyser, exploiter, structurer des données]",Lyon 2E Arrondissement,69002,45.753267,4.826881,CDI,NaN,NaN,NaN,EUR,1.0,Conseil en systèmes et logiciels informatiques,,M1811,10 à 19 salariés,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564866
24,ft_206QKLR,francetravail,https://candidat.francetravail.fr/offres/reche...,Développeur / Développeuse Big Data,AUBER TECH,"En intégrant notre équipe, vous aurez l'opport...",[],Les Lilas,93260,48.879365,2.415862,CDI,NaN,32000.0,50000.0,EUR,NaN,Conseil en systèmes et logiciels informatiques,,M1811,10 à 19 salariés,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564871
25,ft_1239759,francetravail,https://candidat.francetravail.fr/offres/reche...,Data manager,NaN,"Rattaché(e) à Morgane, Directrice du service, ...",[],Bruz,35170,48.024465,-1.746132,CDI,NaN,55000.0,60000.0,EUR,10.0,Réparation d'ordinateurs et d'équipements péri...,,M1811,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564875
26,ft_1235945,francetravail,https://candidat.francetravail.fr/offres/reche...,Responsable architecture conception data,NaN,Description du poste\nAu sein de la branche In...,[],Saint-Ouen-Sur-Seine,93400,48.911659,2.334410,CDI,NaN,NaN,NaN,EUR,5.0,,,M1811,None,[],[],,2026-04-08,2026-04-08T22:44:10.564879
27,ft_1230268,francetravail,https://candidat.francetravail.fr/offres/reche...,Ingénieur / Ingénieure en développement big data,NaN,\n Au sein du Service Systèmes d'I...,[],Orléans,45000,47.912131,1.929164,CDI,NaN,NaN,NaN,EUR,0.0,,,M1811,None,[],[],Manœuvre,2026-04-08,2026-04-08T22:44:10.564884
28,ft_1230142,francetravail,https://candidat.francetravail.fr/offres/reche...,Ingénieur / Ingénieure dataviz,NaN,\n Ce que vous allez faire si vous...,[],Caen,14000,49.193554,-0.390440,CDI,NaN,NaN,NaN,EUR,2.0,,,M1811,None,[],[],Technicien,2026-04-08,2026-04-08T22:44:10.564888
29,ft_1230098,francetravail,https://candidat.francetravail.fr/offres/reche...,Analyste qualité des données,NaN,\n Sous la responsabilité du Respon...,[],Nantes,44000,47.206511,-1.588370,CDI,NaN,NaN,NaN,EUR,2.0,,,M1811,None,[],[],Technicien,2026-04-08,2026-04-08T22:44:10.564891
30,ft_1230039,francetravail,https://candidat.francetravail.fr/offres/reche...,Développeur / Développeuse data,NaN,\n Intégrez l’équipe Atos Strasbou...,[],Strasbourg,67000,48.584715,7.750792,CDI,NaN,NaN,NaN,EUR,2.0,,,M1811,None,[],[],Technicien,2026-04-08,2026-04-08T22:44:10.564895
31,ft_1229952,francetravail,https://candidat.francetravail.fr/offres/reche...,Expert / Experte big data,NaN,\n Missions et responsabilités :...,[],Bezons,95870,48.927790,2.216126,CDI,NaN,NaN,NaN,EUR,5.0,,,M1811,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564899
32,ft_1229744,francetravail,https://candidat.francetravail.fr/offres/reche...,Expert / Experte technique big data,NaN,\n Description de l'entrepriseDescr...,[],Bordeaux,33000,44.832810,-0.611465,CDI,NaN,NaN,NaN,EUR,0.0,,,M1811,None,[],[],Technicien,2026-04-08,2026-04-08T22:44:10.564903
33,ft_1229640,francetravail,https://candidat.francetravail.fr/offres/reche...,Ingénieur / Ingénieure big data,NaN,\n Dans un contexte de croissance d...,[],Paris 1Er Arrondissement,75001,NaN,NaN,CDI,NaN,NaN,NaN,EUR,5.0,,,M1811,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564907
34,ft_1228271,francetravail,https://candidat.francetravail.fr/offres/reche...,Architecte de données informatiques,GROUPE AVANTIS ENGINEERING,RESPONSABILITÉS : \n\nDans la continuité du dé...,[],Magny-Les-Hameaux,78114,48.724020,2.083948,CDD,NaN,38000.0,45000.0,EUR,NaN,,,M1811,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564911
35,ft_1229978,francetravail,https://candidat.francetravail.fr/offres/reche...,Architecte big data,NaN,\n Rejoignez la communauté Data d’...,[],Bezons,95870,48.927790,2.216126,CDI,NaN,NaN,NaN,EUR,10.0,,,M1811,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564914
36,ft_1229972,francetravail,https://candidat.francetravail.fr/offres/reche...,Expert / Experte big data,NaN,\n Missions principales Être le ...,[],Clayes-Sous-Bois,78340,48.821060,1.986412,CDI,NaN,NaN,NaN,EUR,2.0,,,M1811,None,[],[],Cadre,2026-04-08,2026-04-08T22:44:10.564918
37,ft_1226773,francetravail,https://candidat.francetravail.fr/offres/reche...,Développeur / Développeuse data,AKKODIS,La ligne de service Consulting & Solutions d'A...,[],Bordeaux,33000,44.857246,-0.573697,CDI,NaN,35000.0,45000.0,EUR,3.0,Défense,,M1811,None,[],[],,2026-04-08,2026-04-08T22:44:10.564922
38,ft_206MWBD,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,BASSETTI GROUP,Votre rôle se décline en 4 missions.\n\n1. Arc...,"[Analyser, exploiter, structurer des données]",Paris (Dept.),NaN,NaN,NaN,CDI,NaN,45000.0,65000.0,EUR,3.0,Activités des sociétés holding,,M1811,3 à 5 salariés,[],[],Employé qualifié,2026-04-07,2026-04-08T22:44:10.564926
39,ft_1195318,francetravail,https://candidat.francetravail.fr/offres/reche...,Développeur / Développeuse IA,NaN,\n Rejoignez Atos et sa practice Ra...,[],Bezons,95870,48.927790,2.216126,CDI,NaN,NaN,NaN,EUR,5.0,,,M1889,None,[],[],Cadre,2026-04-07,2026-04-08T22:44:10.564930
40,ft_1195279,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,NaN,\n Description de l'entrepriseSopra...,[],Nantes,44000,47.222973,-1.596644,CDD,NaN,NaN,NaN,EUR,0.0,,,M1811,None,[],[],Technicien,2026-04-07,2026-04-08T22:44:10.564934
41,ft_1195240,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,NaN,\n Description de l'entrepriseSopra...,[],Nantes,44000,47.222973,-1.596644,CDD,NaN,NaN,NaN,EUR,0.0,,,M1811,None,[],[],Technicien,2026-04-07,2026-04-08T22:44:10.564938
42,ft_1195159,francetravail,https://candidat.francetravail.fr/offres/reche...,Big data engineer,NaN,\n Ce que vous allez faire si vous...,[],Caen,14000,49.176904,-0.400665,CDI,NaN,NaN,NaN,EUR,2.0,,,M1811,None,[],[],Technicien,2026-04-07,2026-04-08T22:44:10.564942
43,ft_1194763,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,NaN,\n Description de l'entrepriseDescr...,[],Nantes,44000,47.222973,-1.596644,CDI,NaN,NaN,NaN,EUR,0.0,,,M1811,None,[],[],Technicien,2026-04-07,2026-04-08T22:44:10.564946
44,ft_1194620,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,NaN,\n Vos missions à nos côtés :• Co...,[],Bezons,95870,48.927790,2.216126,CDI,NaN,NaN,NaN,EUR,5.0,,,M1811,None,[],[],Cadre,2026-04-07,2026-04-08T22:44:10.564950
45,ft_206PBCY,francetravail,https://candidat.francetravail.fr/offres/reche...,Ingénieur / Ingénieure data scientist,MYRIAD,Consultant ML Engineer Confirmé\n\nContexte :\...,[Adapter les outils de traitement statistique ...,Neuilly Sur Seine,92200,48.884789,2.269688,CDI,NaN,55000.0,60000.0,EUR,3.0,Conseil en systèmes et logiciels informatiques,,M1405,3 à 5 salariés,[],[],Cadre,2026-04-07,2026-04-08T22:44:10.564954
46,ft_1221608,francetravail,https://candidat.francetravail.fr/offres/reche...,Data scientist,NaN,L'utilisation de la data et le développement d...,[],Massy,91300,48.727791,2.275131,CDI,NaN,NaN,NaN,EUR,5.0,Commerce d'alimentation générale,,M1405,None,[],[],Cadre,2026-04-07,2026-04-08T22:44:10.564958
47,ft_206NCZS,francetravail,https://candidat.francetravail.fr/offres/reche...,Data engineer,ATMOSUD PROVENCE ALPES COTE D'AZUR,Nous recrutons un(e) Ingénieur(e) Data Industr...,"[Programmation en Python, Système d'exploitati...",Marseille,13006,43.288326,5.387368,CDD,NaN,34000.0,40000.0,EUR,1.0,"Analyses, essais et inspections techniques",,M1811,20 à 49 salariés,[],[],Cadre,2026-04-07,2026-04-08T22:44:10.564962
48,ft_1215925,francetravail,https://candidat.francetravail.fr/offres/reche...,Data manager,NaN,Description du poste :\nEn postulant à cette o...,[],Paris 9E Arrondissement,75009,48.872479,2.341194,CDI,NaN,70000.0,100000.0,EUR,3.0,,,M1811,None,[],[],,2026-04-07,2026-04-08T22:44:10.564966
49,ft_1211110,francetravail,https://candidat.francetravail.fr/offres/reche...,Data manager,NaN,Description du poste :\nEn tant qu'organisateu...,[],Hauts-De-Seine,NaN,NaN,NaN,CDI,NaN,NaN,NaN,EUR,3.0,,,M1811,None,[],[],,2026-04-07,2026-04-08T22:44:10.564970
50,ft_1211010,francetravail,https://candidat.francetravail.fr/offres/reche...,Data manager,NaN,Description du poste :\nEn tant qu'organisateu...,[],Isère,NaN,NaN,NaN,CDI,NaN,NaN,NaN,EUR,NaN,,,M1811,None,[],[],,2026-04-07,2026-04-08T22:44:10.564974
51,ft_1209828,francetravail,https://candidat.francetravail.fr/offres/reche...,Data manager,NaN,Description du poste :\nEn tant qu'organisateu...,[],Rhône,NaN,NaN,NaN,CDI,NaN,NaN,NaN,EUR,NaN,,,M1811,None,[],[],,2026-04-07,2026-04-08T22:44:10.564978
52,ft_1208889,francetravail,https://candidat.francetravail.fr/offres/reche...,Data manager,NaN,Description du poste :\nEn tant qu'organisateu...,[],Paris,NaN,NaN,NaN,CDI,NaN,NaN,NaN,EUR,1.0,,,M1811,None,[],[],,2026-04-07,2026-04-08T22:44:10.564981
53,ft_1206275,francetravail,https://candidat.francetravail.fr/offres/reche...,Data manager,NaN,Description du poste Job Description:***Airbus...,[],Toulouse,31000,43.597868,1.430199,CDI,NaN,NaN,NaN,EUR,NaN,,,M1811,None,[],[],,2026-04-07,2026-04-08T22:44:10.564985
54,ft_1195326,francetravail,https://candidat.francetravail.fr/offres/reche...,Développeur / Développeuse data,NaN,\n Rejoignez la communauté Data d’A...,[],Bordeaux,33000,44.873213,-0.546046,CDI,NaN,NaN,NaN,EUR,2.0,,,M1811,None,[],[],Cadre,2026-04-07,2026-04-08T22:44:10.564990
55,ft_206NVDS,francetravail,https://candidat.francetravail.fr/offres/reche...,Développeur / Développeuse Big Data,VPEX IT,Nous recherchons un(e) Data Ingénieur Big Data...,"[Data engineer, Analyser, exploiter, structure...",Levallois-Perret,92300,48.892818,2.287751,CDI,NaN,35000.0,54000.0,EUR,3.0,Conseil en systèmes et logiciels informatiques,,M1811,6 à 9 salariés,[],[],Cadre,2026-04-07,2026-04-08T22:44:10.564993

In [52]:
df.describe()

         latitude   longitude   salaire_min    salaire_max  experience_min
count  105.000000  105.000000     28.000000      27.000000       90.000000
mean    47.651379    1.933754  43178.571429   53514.814815        3.094444
std      1.964145    2.432976  12406.848680   14742.995826        2.736452
min     43.288326   -1.746132  10000.000000   20000.000000        0.000000
25%     47.194026   -0.390440  38000.000000   45000.000000        1.000000
50%     48.724020    2.216126  39000.000000   50000.000000        2.500000
75%     48.911659    2.415862  46250.000000   60000.000000        5.000000
max     50.628200    7.782983  78000.000000  100000.000000       10.000000

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  120 non-null    str
 1   source              120 non-null    str
 2   url                 120 non-null    str
 3   titre               120 non-null    str
 4   entreprise          45 non-null     str
 5   description         120 non-null    str
 6   competences         120 non-null    object
 7   localisation_ville  120 non-null    str
 8   localisation_dept   103 non-null    str
 9   latitude            105 non-null    float64
 10  longitude           105 non-null    float64
 11  type_contrat        120 non-null    str
 12  teletravail         20 non-null     str
 13  salaire_min         28 non-null     float64
 14  salaire_max         27 non-null     float64
 15  salaire_devise      110 non-null    str
 16  experience_min      90 non-null     float64
 17  secteur             120 non-null    str
 18  sous_secteur        120 non-null    str
 19  rome_code           120 non-null    str
 20  nb_employes         31 non-null     object
 21  missions            120 non-null    object
 22  avantages           120 non-null    object
 23  qualification       120 non-null    str
 24  date_publication    120 non-null    str
 25  date_extraction     120 non-null    str
dtypes: float64(5), object(4), str(17)
memory usage: 24.5+ KB

In [54]:
df['source'].value_counts()

source
francetravail         100
welcometothejungle     20
Name: count, dtype: int64